spring:
  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&serverTimezone=UTC
    username: 7Nm8DEXSFH8SgY8.app_user
    password: strong_password

  jpa:
    hibernate:
      ddl-auto: update   # dev only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
